---
- name: check java running
  include_role:
    name: java

- name: check if wellsfargo process is running
  shell: ps -ef | if grep -q "[w]orkerGroup"; then echo yes; else echo no; fi
  register: wellsfargo_running

- name: start wellsfargo process if not running
  shell: nohup java -jar /opt/pipeline/TaskRunner-1.0.jar --workerGroup=wg-wellsfargo --region=us-east-1 --logUri=s3://annalect-datapipeline-logs/WellsFargo &
  when: wellsfargo_running.stdout == "no"

- name: check if wellsfargo process is running 2nd
  shell: ps -ef | if grep -q "[w]orkerGroup"; then echo yes; else echo no; fi
  register: wellsfargo_running_2nd_check

- fail: msg="wellsfargo process not running"
  when: wellsfargo_running_2nd_check.stdout == "no"
