---
#
# This role backups/updates a wordpress site using WP_CLI
#

- fail: msg='Variable `only_backup` has to be specified when running the playbook. Please use option `-e {only_backup:True|False}` to run the playbook'
  when: only_backup is undefined

- name: setting only_backup to a boolean value
  set_fact:
    only_backup: "{{ only_backup | bool }}"

- name: set timestamp
  shell: date +%Y%m%d-%H%M
  register: timestamp

- name: set wordpress base dir
  shell: echo $(basename $(pwd))
  args:
    chdir: "{{ wordpress_path }}"
  register: wordpress_basename

- name: remove current management user
  user:
    name: "{{ management_user }}"
    state: absent
  become: yes

- name: create user group if it doesn't exist
  group:
    name: "{{ management_user }}"
    state: present
  become: yes

- name: add management user to perform the update
  user:
    name: "{{ management_user }}"
    state: present
    force: yes
    group: "{{ management_user }}"
  become: yes

- name: set management user wordpress home path
  shell: grep {{ management_user }} /etc/passwd | cut -d ":" -f6
  become: yes
  register: management_user_home

- name: set facts to be used later
  set_fact:
    timestamp: "{{ timestamp.stdout}}"
    wpcli_command: "{{ management_user_home.stdout }}/wp"
    management_user_home: "{{ management_user_home.stdout }}"
    wordpress_basename: "{{ wordpress_basename.stdout }}"
    wordpress_path_parent: "{{ wordpress_path }}/.."

- name: set facts to be used later
  set_fact:
    wordpress_backup_basename_db: "{{ wordpress_basename }}-backup-db"
    wordpress_backup_basename_site: "{{ wordpress_basename }}-backup-site"

- name: set facts to be used later
  set_fact:
    wordpress_backup_name_db: "{{ wordpress_backup_basename_db }}-{{ timestamp }}.sql"

- name: set facts to be used later
  set_fact:
    wordpress_backup_name_db_compressed: "{{ wordpress_backup_name_db }}.gz"
    wordpress_backup_name_site_compressed: "{{ wordpress_backup_basename_site }}-{{ timestamp }}.tar.gz"

- name: verify if WP-CLI is installed
  shell: ls {{ wpcli_command }}
  ignore_errors: yes
  register: wpcli_command_correct

- include_tasks: wpcli_install.yml
  when: wpcli_command_correct.rc > 0

- name: update wp-cli
  shell: sudo --user {{ management_user }} -- {{ wpcli_command }} cli update --yes
  register: update_wp_cli_result
  ignore_errors: yes

- debug: msg="ERROR UPDATING WP-CLI, PLEASE REVIEW"
  when: update_wp_cli_result.rc > 0

- name: change group for wordpress path to management user group
  shell: chgrp {{ management_user }} -R {{ wordpress_path }}
  become: yes

- name: add write permission to management user group for wordpress path
  shell: chmod g+w -R {{ wordpress_path }}
  become: yes

- name: taking backup of website
  include_tasks: backup_site.yml

# - name: removing old database backups if any
#   shell: rm {{ wordpress_backup_basename_db }}* || true
#   args:
#     chdir: "{{ wordpress_path }}"
#   become: yes

# - name: dump and compress wordpress db
#   shell: sudo --user {{ management_user }} --
#     {{ wpcli_command }} db export --quiet {{ wordpress_backup_name_db }} &&
#     sudo --user {{ management_user }} -- gzip {{ wordpress_backup_name_db }}
#   args:
#     chdir: "{{ wordpress_path }}"

# - name: remove old site backups if any
#   shell: rm {{ wordpress_backup_basename_site }}* || true
#   args:
#     chdir: "{{ wordpress_path_parent }}"
#   become: yes

# - name: backup wordpress folder with database dump inside
#   shell: tar czf {{ wordpress_backup_name_site_compressed }} {{ wordpress_basename }}
#   args:
#     chdir: "{{ wordpress_path_parent }}"
#   become: yes

# - name: upload backup to S3
#   shell: aws --region {{ ec2_region }} s3 cp {{ wordpress_backup_name_site_compressed }}
#     s3://annalect-backups/wordpress/{{ sitename }}/ --sse
#   args:
#     chdir: "{{ wordpress_path_parent }}"

- name: update wordpress plugins
  shell: sudo --user {{ management_user }} -- {{ wpcli_command }} plugin update --all
  args:
    chdir: "{{ wordpress_path }}"
  when: not only_backup

- name: update all wordpress themes
  shell: sudo --user {{ management_user }} -- {{ wpcli_command }} theme update --all
  args:
    chdir: "{{ wordpress_path }}"
  when: not only_backup

- name: update wordpress core
  shell: sudo --user {{ management_user }} --  {{ wpcli_command }} core update --minor
  args:
    chdir: "{{ wordpress_path }}"
  when: not only_backup

- name: remove management user
  user:
    name: "{{ management_user }}"
    state: absent
  become: yes

- name: remove management group
  group:
    name: "{{ management_user }}"
    state: absent
  become: yes

- name: template hardening script to <wordpress_path_parent>
  template:
    src: templates/{{ post_upgrade_hardening_script_name }}.j2
    dest: "{{ wordpress_path_parent }}/{{ post_upgrade_hardening_script_name }}"
    mode: ugo+x
  become: yes

- name: execute hardening script
  shell: "{{ wordpress_path_parent }}/{{ post_upgrade_hardening_script_name }}"
  ignore_errors: yes
  become: yes

# - name: remove site backups
#   shell: rm {{ wordpress_backup_name_site_compressed }}
#   args:
#     chdir: "{{ wordpress_path_parent }}"
#   become: yes

# - name: remove database backup
#   shell: rm {{ wordpress_backup_name_db_compressed }}
#   args:
#     chdir: "{{ wordpress_path }}"
#   become: yes

- name: remove hardening script
  shell: rm {{ post_upgrade_hardening_script_name }}
  args:
    chdir: "{{ wordpress_path_parent }}"
  become: yes
