---
- name: download wpcli
  become: true
  shell: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  args:
    chdir: "{{ management_user_home }}"

- name: configure wp command
  become: yes
  shell: mv {{ management_user_home }}/wp-cli.phar {{ wpcli_command }} &&
    chmod +x {{ wpcli_command }} &&
    chgrp {{ management_user }} {{ wpcli_command }} &&
    chmod g+w {{ wpcli_command }}

- name: see if command wp works
  shell: "{{ wpcli_command }} --info"

