---
- set_fact:
    check_ubuntu_release: {"stdout": ""}
    check_reboot_required: {"stdout": ""}
    check_kernelVersion: {"stdout": ""}
    check_logstash: {"stdout": ""}
    check_logstash_autostart: {"stdout": ""}
    check_apache2_running: {"stdout": ""}
    check_apache2_version: {"stdout": ""}
    check_apache2_errorLogFormat: {"stdout": ""}
    check_filebeat_uninstalled: {"stdout": ""}
    check_patrol_running: {"stdout": ""}
    check_java_running: {"stdout": ""}
    check_java_version: {"stdout": ""}
    check_mesos_version: {"stdout": ""}
    check_mesos_master_running: {"stdout": ""}
    check_mesos_slave_running: {"stdout": ""}
    check_marathon_version: {"stdout": ""}
    check_marathon_running: {"stdout": ""}
    check_zookeeper_version: {"stdout": ""}
    check_zookeeper_running: {"stdout": ""}
    check_aubi_running: {"stdout": ""}
    check_dsdk_running: {"stdout": ""}
    check_taskrunner_running: {"stdout": ""}
    check_mongodb_running: {"stdout": ""}
    check_mongodb_version: {"stdout": ""}
    check_bamboo_running: {"stdout": ""}
    check_samba_running: {"stdout": ""}
    check_openvpnas_running: {"stdout": ""}
    check_openvpnas_version: {"stdout": ""}
    check_openswan_running: {"stdout": ""}
    check_openswan_version: {"stdout": ""}
    check_sophos_running: {"stdout": ""}
    check_datadogagent_running: {"stdout": ""}
    check_updates_regular_critical: {"stderr": ""}
  tags: always

- name: check pending updates
  shell: /usr/lib/update-notifier/apt-check
  register: check_updates_regular_critical
  tags: system
  ignore_errors: yes

- name: if check_updates_regular_critical failed, register 'error'
  set_fact:
    check_updates_regular_critical: "error;error"
  when: check_updates_regular_critical is failed

- name: check reboot required
  shell: if [ -f /var/run/reboot-required ]; then echo yes; else echo no; fi
  become: yes
  register: check_reboot_required
  tags: system

- name: check kernel version
  shell: uname -r
  register: check_kernelVersion
  tags: system

- name: check ubuntu release
  shell: lsb_release -r || true
  register: check_ubuntu_release
  tags: system

- name: check logstash is running
  shell: ps ax |  grep -v grep | if grep -q "org.logstash.Logstash"; then echo yes; else echo no; fi
  register: check_logstash
  tags: logstash

- name: check logstash-autostart is running
  shell: ps ax | grep -v grep | if grep -q "logstash-autostart.sh"; then echo yes; else echo no; fi
  register: check_logstash_autostart
  tags: logstash

- name: apache2 service is running
  shell: service apache2 status | if grep -q "is running"; then echo yes; else echo no; fi
  become: yes
  register: check_apache2_running
  tags: apache

- name: check apache2 version
  shell: dpkg -s apache2 2>&1 | grep '^Version:'
  become: yes
  ignore_errors: yes
  register: check_apache2_version
  tags: apache

- name: check filebeat
  shell: ps ax | grep -v grep | if grep -q "filebeat"; then echo yes; else echo no; fi
  register: check_filebeat_uninstalled
  tags: filebeat

- name: check patrol agent
  shell: ps ax | grep -v grep | if grep -q "[P]atrolAgent"; then echo yes; else echo no; fi
  register: check_patrol_running
  tags: patrol

- name: ErrorLogFormat in /etc/apache2/apache2.conf
  shell: |
         if [ -f /etc/apache2/apache2.conf ];
         then
            if cat /etc/apache2/apache2.conf | grep -q ErrorLogFormat;
            then
              grep ErrorLogFormat /etc/apache2/apache2.conf;
            else
              echo 'no ErrorLogFormat directive';
            fi;
         else
            echo 'NO FILE';
         fi
  become: yes
  register: check_apache2_errorLogFormat
  tags: apache

- name: check java
  shell: ps ax | grep -v grep | if grep -q "[jJ]ava"; then echo yes; else echo no; fi
  become: yes
  register: check_java_running
  tags: java

- name: check java version
  shell: java -version 2>&1 | grep version
  ignore_errors: yes
  become: yes
  register: check_java_version
  tags: java

- name: check mesos-master running
  shell: ps ax | grep -v grep | if grep -q $(which mesos-master); then echo yes; else echo no; fi
  ignore_errors: yes
  become: yes
  register: check_mesos_master_running
  tags: mesos

- name: check mesos-slave running
  shell: ps ax | grep -v grep | if grep -q $(which mesos-slave); then echo yes; else echo no; fi
  ignore_errors: yes
  become: yes
  register: check_mesos_slave_running
  tags: mesos

- name: check mesos version
  shell: dpkg -s mesos 2>&1 | grep '^Version:'
  ignore_errors: yes
  become: yes
  register: check_mesos_version
  tags: mesos

- name: check marathon running
  shell: echo $(service marathon status) | sed 's/;/-/g' | sed 's/,/ /g'
  ignore_errors: yes
  become: yes
  register: check_marathon_running
  tags: marathon

- name: check marathon version
  shell: dpkg -s marathon 2>&1 | grep '^Version:'
  ignore_errors: yes
  become: yes
  register: check_marathon_version
  tags: marathon

- name: check zookeper running
  shell: echo $(service zookeeper status) | sed 's/;/-/g' | sed 's/,/ /g'
  ignore_errors: yes
  become: yes
  register: check_zookeeper_running
  tags: zookeper

- name: check zookeper version
  shell: dpkg -s zookeeper 2>&1 | grep '^Version:'
  ignore_errors: yes
  become: yes
  register: check_zookeeper_version
  tags: zookeper

- name: check aubi running
  shell: ps ax | grep -v grep | if grep -q "[l]abs_sso"; then echo yes; else echo no; fi
  ignore_errors: yes
  become: yes
  register: check_aubi_running
  tags: aubi

- name: check dsdk running
  shell: ps ax | grep -v grep | if grep -q "[d]sdk_process.py"; then echo yes; else echo no; fi
  ignore_errors: yes
  become: yes
  register: check_dsdk_running
  tags: dsdk

- name: check task runner running
  shell: ps ax | grep -v grep | if grep -q "[w]orkerGroup"; then echo yes; else echo no; fi
  ignore_errors: yes
  become: yes
  register: check_taskrunner_running
  tags: taskrunner

- name: check mongodb running
  shell: ps ax | grep -v grep | if grep -q "[m]ongod"; then echo yes; else echo no; fi
  ignore_errors: yes
  become: yes
  register: check_mongodb_running
  tags: mongodb

- name: check mongodb version
  shell: echo $(mongod --version) | sed 's/;/-/g' | sed 's/,/ /g'
  ignore_errors: yes
  become: yes
  register: check_mongodb_version
  tags: mongodb

- name: check bamboo running
  shell: ps ax | grep -v grep | if grep -q "[b]amboo"; then echo yes; else echo no; fi
  ignore_errors: yes
  become: yes
  register: check_bamboo_running
  tags: bamboo

- name: check samba running
  shell: echo $(service smbd status) | sed 's/;/-/g' | sed 's/,/ /g'
  ignore_errors: yes
  become: yes
  register: check_samba_running
  tags: samba

- name: check openvpnas running
  shell: ps ax | grep -v grep | if grep -q "[o]penvpnas"; then echo yes; else echo no; fi
  ignore_errors: yes
  become: yes
  register: check_openvpnas_running
  tags: openvpn

- name: check openvpnas version
  shell: dpkg -s openvpn-as | grep '^Version:'
  ignore_errors: yes
  become: yes
  register: check_openvpnas_version
  tags: openvpn

- name: check openswan running
  shell: ps ax | grep -v grep | if grep -q "[i]psec"; then echo yes; else echo no; fi
  ignore_errors: yes
  become: yes
  register: check_openswan_running
  tags: openswan

- name: check openswan version
  shell: echo $(ipsec --version) | sed 's/;/-/g' | sed 's/,/ /g'
  ignore_errors: yes
  become: yes
  register: check_openswan_version
  when: check_openvpnas_running.stdout == "yes"
  tags: openswan

- name: check sophos running
  shell: ps ax | grep -v grep | if grep -q "[s]ophos"; then echo yes; else echo no; fi
  ignore_errors: yes
  become: yes
  register: check_sophos_running
  tags: sophos

- name: check datadog agent running
  shell: ps ax | grep -v grep | if grep -q "[d]atadog-agent"; then echo yes; else echo no; fi
  ignore_errors: yes
  become: yes
  register: check_datadogagent_running
  tags: datadog

- name: generating summary file
  local_action: template src=templates/report1.j2 dest=tmp/report-{{ ec2_tag_Environment | default("") }}-{{ ec2_tag_Application | default("") }}-{{ ec2_private_ip_address | default("") }}.csv
  tags: always

