---
- name: including vaulted vars
  tags: always
  include_vars:
    file: vars/vault

#- debug: var=ec2_tag_Environment
#
#- fail: msg="its a dev"
#  when: ec2_tag_Environment == "Dev"
#
#- fail:

- name: fail if ec2_tag_ServiceGroup is not defined
  fail:
  when: ec2_tag_ServiceGroup is not defined

- name: including official Datadog role (service group "general")
  tags: general
  become: yes
  when:
    - ec2_tag_ServiceGroup == "general"
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_config:
        apm_enabled: "false" # has to be set as a string
        log_enabled: false   # log collection is available on agent 6
        datadog_agent_version: "1:6.0.0-1"
        process_config:
          enabled: "true" # has to be set as a string
          scrub_args: true
          custom_sensitive_words: ['consul_token','dd_api_key']
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
            exact_match: false

- name: including official Datadog role (service group "apache")
  tags: apache
  become: yes
  when:
    - ec2_tag_ServiceGroup == "apache"
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_config:
        apm_enabled: "false" # has to be set as a string
        log_enabled: false   # log collection is available on agent 6
        datadog_agent_version: "1:6.0.0-1"
        process_config:
          enabled: "true" # has to be set as a string
          scrub_args: true
          custom_sensitive_words: ['consul_token','dd_api_key']
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
            exact_match: false
          - name: apache
            search_string: ['apache2']
            exact_match: false

- name: including official Datadog role (service group "mesos-slave")
  tags: mesos-slave
  become: yes
  when:
    - ec2_tag_ServiceGroup == "mesos-slave"
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_config:
        apm_enabled: "false" # has to be set as a string
        log_enabled: false   # log collection is available on agent 6
        datadog_agent_version: "1:6.0.0-1"
        process_config:
          enabled: "true" # has to be set as a string
          scrub_args: true
          custom_sensitive_words: ['consul_token','dd_api_key']
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
            exact_match: false
          - name: logstash
            search_string: ['org.logstash.Logstash']
            exact_match: false
          - name: logstash-autostart
            search_string: ['logstash-autostart']
            exact_match: false
          - name: mesos-slave
            search_string: ['mesos-slave']
            exact_match: false
          - name: apache
            search_string: ['apache2']
            exact_match: false

- name: including official Datadog role (service group "mesos-master")
  tags: mesos-master
  become: yes
  when:
    - ec2_tag_ServiceGroup == "mesos-master"
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_config:
        apm_enabled: "false" # has to be set as a string
        log_enabled: false   # log collection is available on agent 6
        datadog_agent_version: "1:6.0.0-1"
        process_config:
          enabled: "true" # has to be set as a string
          scrub_args: true
          custom_sensitive_words: ['consul_token','dd_api_key']
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
            exact_match: false
          - name: mesos-master
            search_string: ['mesos-master']
            exact_match: false
          - name: marathon
            search_string: ['mesosphere.marathon.Main']
            exact_match: false

- name: including official Datadog role (service group "analysis")
  tags: analysis
  become: yes
  when:
    - ec2_tag_ServiceGroup == "analysis"
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_config:
        apm_enabled: "false" # has to be set as a string
        log_enabled: false   # log collection is available on agent 6
        datadog_agent_version: "1:6.0.0-1"
        process_config:
          enabled: "true" # has to be set as a string
          scrub_args: true
          custom_sensitive_words: ['consul_token','dd_api_key']
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
            exact_match: false
          - name: labs_sso
            search_string: ['abs_sso'] # abs_sso written on purpose
            exact_match: false

- name: including official Datadog role (service group "dsdk")
  tags: dsdk
  become: yes
  when:
    - ec2_tag_ServiceGroup == "dsdk"
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_config:
        apm_enabled: "false" # has to be set as a string
        log_enabled: false   # log collection is available on agent 6
        datadog_agent_version: "1:6.0.0-1"
        process_config:
          enabled: "true" # has to be set as a string
          scrub_args: true
          custom_sensitive_words: ['consul_token','dd_api_key']
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
            exact_match: false
          - name: dsdk_process
            search_string: ['sdk_process.py'] # sdk_process written on purpose
            exact_match: false

- name: including official Datadog role (service group "wellsfargo")
  tags: wellsfargo
  become: yes
  when:
    - ec2_tag_ServiceGroup == "wellsfargo"
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_config:
        apm_enabled: "false" # has to be set as a string
        log_enabled: false   # log collection is available on agent 6
        datadog_agent_version: "1:6.0.0-1"
        process_config:
          enabled: "true" # has to be set as a string
          scrub_args: true
          custom_sensitive_words: ['consul_token','dd_api_key']
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
            exact_match: false
          - name: java
            search_string: ['java']
            exact_match: false
          - name: workerGroup
            search_string: ['orkerGroup'] # orkerGroup written on purpose
            exact_match: false

- name: including official Datadog role (service group "utility")
  tags: utility
  become: yes
  when:
    - ec2_tag_ServiceGroup == "utility"
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_config:
        apm_enabled: "false" # has to be set as a string
        log_enabled: false   # log collection is available on agent 6
        datadog_agent_version: "1:6.0.0-1"
        process_config:
          enabled: "true" # has to be set as a string
          scrub_args: true
          custom_sensitive_words: ['consul_token','dd_api_key']
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
            exact_match: false
          - name: workerGroup
            search_string: ['orkerGroup'] # orkerGroup written on purpose
            exact_match: false

- name: including official Datadog role (service group "mongodb")
  tags: mongodb
  become: yes
  when:
    - ec2_tag_ServiceGroup == "mongodb"
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_config:
        apm_enabled: "false" # has to be set as a string
        log_enabled: false   # log collection is available on agent 6
        datadog_agent_version: "1:6.0.0-1"
        process_config:
          enabled: "true" # has to be set as a string
          scrub_args: true
          custom_sensitive_words: ['consul_token','dd_api_key']
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
            exact_match: false
          - name: mongodb
            search_string: ['mongod']
            exact_match: false

- name: including official Datadog role (service group "bamboo")
  tags: bamboo
  become: yes
  when:
    - ec2_tag_ServiceGroup == "bamboo"
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_config:
        apm_enabled: "false" # has to be set as a string
        log_enabled: false   # log collection is available on agent 6
        datadog_agent_version: "1:6.0.0-1"
        process_config:
          enabled: "true" # has to be set as a string
          scrub_args: true
          custom_sensitive_words: ['consul_token','dd_api_key']
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
          - name: java
            search_string: ['java']
            exact_match: false
          - name: bamboo
            search_string: ['amboo'] # amboo written on purpose
            exact_match: false

- name: including official Datadog role (service group "samba")
  tags: samba
  become: yes
  when:
    - ec2_tag_ServiceGroup == "samba"
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_config:
        apm_enabled: "false" # has to be set as a string
        log_enabled: false   # log collection is available on agent 6
        datadog_agent_version: "1:6.0.0-1"
        process_config:
          enabled: "true" # has to be set as a string
          scrub_args: true
          custom_sensitive_words: ['consul_token','dd_api_key']
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
            exact_match: false
          - name: smbd
            search_string: ['smbd']
            exact_match: false

- name: including official Datadog role (service group "openvpn")
  tags: openvpn
  become: yes
  when:
    - ec2_tag_ServiceGroup == "openvpn"
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_config:
        apm_enabled: "false" # has to be set as a string
        log_enabled: false   # log collection is available on agent 6
        datadog_agent_version: "1:6.0.0-1"
        process_config:
          enabled: "true" # has to be set as a string
          scrub_args: true
          custom_sensitive_words: ['consul_token','dd_api_key']
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
            exact_match: false
          - name: openvpnas
            search_string: ['openvpnas']
            exact_match: false

- name: including official Datadog role (service group "openswan")
  tags: openswan
  become: yes
  when:
    - ec2_tag_ServiceGroup == "openswan"
  include_role:
    name: Datadog.datadog
  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_config:
        apm_enabled: "false" # has to be set as a string
        log_enabled: false   # log collection is available on agent 6
        datadog_agent_version: "1:6.0.0-1"
        process_config:
          enabled: "true" # has to be set as a string
          scrub_args: true
          custom_sensitive_words: ['consul_token','dd_api_key']
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
            exact_match: false
          - name: ipsec
            search_string: ['ipsec']
            exact_match: false
