---
- name: check if dsdk process is running
  shell: ps -ef | if grep -q "[d]sdk_process.py"; then echo yes; else echo no; fi
  register: dsdk_running

- name: start aubi service if not running
  shell: sudo --user dt-admin -- nohup python /home/dt-admin/multi_client_data_feed/dsdk_file_processing/dsdk_process.py &
  when: dsdk_running.stdout == "no"

- name: check if dsdk process is running 2nd
  shell: ps -ef | if grep -q "[d]sdk_process.py"; then echo yes; else echo no; fi
  register: dsdk_running_2nd_check

- fail: msg="dsdk process not running"
  when: dsdk_running_2nd_check.stdout == "no"
