---
- name: mesos-slave running
  service:
    name: mesos-slave
    state: started

- name: restart apache
  service:
    name: apache2
    state: restarted

- name: restart logstash-autostart
  shell: nohup /opt/logstash-autostart.sh &
