---
- hosts: us-east-1:&tag_Environment_Prod:&tag_Application_ade:&tag_Layer_ingest

  vars_prompt:
    - name: "refresh_s3"
      prompt: "Refresh logstash-autostart in S3? (y/N)"
      private: no
      default: n

    - name: "copy_script_to_server"
      prompt: "Copy logstash-autostart.sh to /opt on servers? (y/N)"
      private: no
      default: n

    - name: "restart_logstasg_autostart"
      prompt: "Restart logstash-autostart.sh in servera ? (y/N)"
      private: no
      default: n

  tasks:
#    - name: Copy logstash-autostart.sh to S3
#      when: refresh_s3=="y"
#      aws_s3:
#        bucket: annalect.bootstrap-bucket
#        object: /ade/Dev/US/ingest/logstash-autostart.sh
#        src: /Users/anmichel.rodriguez/Documents/projects/devops/helper-scripts/ansible-playbooks/devops/helper-scripts/autostart-scripts/logstash-autostart.sh
#        mode: put


#    - name: check if start_logstash.sh is running
#      shell: pgrep start_logstash.sh > /dev/null && echo RUNNING || echo NOT_RUNNING
#      register: running
#    - debug:
#        msg: running.stdout


  # - name: Checking if Loggly is running
  #   # shell: ps ax | if grep -q "/opt/logstash/lib/logstash/runner.rb agent -f logstash-loggly-mesos.conf"; then echo SI; else echo NO; fi
  #   shell: ps ax | if grep -q "/opt/logstash/lib/logstash/runner.rb agent -f logstash-loggly-mesos.conf"; then echo SI; else echo NO; fi
  #   register: vari


   - name: Copy shell script to start Logstash
     become: yes
     copy:
       src: devops/helper-scripts/autostart-scripts/logstash-autostart.sh
       dest: /opt/logstash-autostart.sh
       owner: root
       group: root
       mode: 0755
     register: copied

  # - name: commenting old cd /opt/logstash line
  #   become: yes
  #   backup: yes
  #   replace:
  #     path: /etc/rc.local
  #     regexp: '^(.*logstash.*)$'
  #     replace: '#1 \1'
  #     backup: yes

  # - name: check rc.local if starting loggly
  #   become: yes
  #   lineinfile:
  #     backup: yes
  #     path: /etc/rc.local
  #     line: "/etc/logstash-autostart.sh 1>&2 &"
      # regexp: "^/etc/logstash-autostart.sh"
      # state: present

   - name: (Re)Starting logstash-autostart.sh
     become: yes
     shell: nohup /opt/logstash-autostart.sh &
     when: copied is changed
     changed_when: no


  # - name: killing any start_logstash.sh
  #   become: yes
  #   shell: pkill -f start_logstash.sh
  #   when: running.stdout == "RUNNING"

  # - name: check if logstash is running
  #   become: yes
  #   shell: pgrep -f "/opt/logstash/lib/logstash/runner.rb agent -f logstash-loggly-mesos.conf" > /dev/null && echo RUNNING || echo NOT_RUNNING
  #   register: running_logstash

  # - name: killing any logstash process running
  #   become: yes
  #   shell: pkill -f "/opt/logstash/lib/logstash/runner.rb agent -f logstash-loggly-mesos.conf" > /dev/null && echo RUNNING || echo NOT_RUNNING
  #   when: running_logstash.stdout == "RUNNING"

  # - name: starting start_logstash.sh
  #   become: yes
  #   shell: nohup /etc/start_logstash.sh &



