---
- hosts: "!platform_windows:&tag_Monitoring_datadog:&~tag_Environment_[dD]ev"
#  tags: always
  become: yes
#  strategy: free
  tasks:
    - name: make directory
      file:
        state: directory
        path: /opt/fireeye

    - name: copy binary
      copy:
        src: fireeye/IMAGE_HX_AGENT_LINUX_32.30.0.tgz
        dest: /opt/fireeye

    - name: uncompress
      command:
        chdir: /opt/fireeye
        cmd: tar xzf IMAGE_HX_AGENT_LINUX_32.30.0.tgz
        creates: agent_config.json

    - name: execute installation
      command:
        chdir: /opt/fireeye
        cmd: dpkg -i xagt_32.30.0-1.ubuntu16_amd64.deb

    - name: configure FireEye
      become: yes
      command:
        cmd: bin/xagt -i agent_config.json
        chdir: /opt/fireeye

    - name: start FireEye agent
      service:
        name: xagt
        state: started
