#
# requires role: https://github.com/dhoeric/ansible-aws-ssm.git
#

- hosts: localhost
  tasks:
  - include_role:
      name: execute_with_script

- hosts: us-east-1:&tag_tower_unixub
  # strategy: free
  # any_errors_fatal: true
  tasks:

  - include_role:
      name: ansible-aws-ssm
