---
#
# To control if patching process (un)holds packages, this playbook can be run with the options:
#     $ ansible-playbook patch-qa.yml
#           [ -e upgrade_distribution=true|false ]
#           [ -e unhold_packages=true|false ] [ -e unhold_mesos_slave=yes|no ]
#           [ -e unhold_mesos_slave=true|false ]
#
# Packages are held by default
- hosts:
    tag_Environment_Prod
    :&tag_tower_unixub
    :!tag_aws_autoscaling_groupName_*
    :!tag_ServiceGroup_openvpn
    :!tag_ServiceGroup_docker
    :!tag_Application_rsyslog
    :!tag_Application_pipeline
    :!tag_Application_netherland
    :!tag_Layer_ecs:!platform_windows
  any_errors_fatal: true
  become: yes
  tasks:
  - name: including patching role
    include_role:
      name: patching
    tags: always
