---
#
# To control if patching process (un)holds packages, this playbook can be run with the options:
#     $ ansible-playbook patch-dev.yml [ -e unhold_packages=yes|no ] [ -e unhold_mesos_slave=yes|no ]
#
# Packages are held by default

- hosts:
    tag_Environment_Dev
    :&tag_tower_unixub
    :!tag_ServiceGroup_docker
    :!tag_Application_rsyslog
    :!tag_Application_pipeline
    :!tag_Application_netherland
    :!tag_Layer_ecs:!platform_windows
  become: yes
  vars_prompt:
    - name: mongodb_backup_done
      prompt: "Did you take a backup of MongoDB? (y/N)"
      private: no
      default: no

  tasks:
#  - fail: var=limit

  - name: fail if mongodb backup not done
    fail: msg="Please take a backup of MongoDB before proceeding (bamboo job? https://bamboo.annalect.com/build/admin/edit/editBuildTasks.action?buildKey=CRON-MONBKP-JOB1)"
    when: not mongodb_backup_done

  - name: setting `unhold_packages` to False if not set
    set_fact:
      unhold_packages: False
    when: unhold_packages is not defined

  - name: setting `unhold_mesos_slave` to False if not set
    set_fact:
      unhold_mesos_slave: False
    when: unhold_mesos_slave is not defined

  - name: including patching role
    include_role:
      name: patching
    vars:
      upgrade_distribution: no
    tags: always
