---
#- hosts: us-east-1:!platform_windows:!tag_Layer_ami:!tag_Layer_ecs:!tag_Application_bmcmonitor:!tag_Application_pipeline:!tag_Application_rsyslog:!tag_Application_bamboo:!tag_Application_openvpn:!tag_Application_jumpshot:!tag_Application_mgmt #10.5.231.234 #us-east-1:!platform_windows
#- hosts: localhost
#  connection: local
#  tasks:
#  - name: making one summary file
#    delegate_to: localhost
#    shell: rm tmp/report-* tmp/summary*
#    ignore_errors: yes

#- hosts: tag_Environment_Dev:tag_Environment_QA:tag_Environment_Prod:tag_Environment_MGMT
#    :&us-east-1:&tag_tower_unixub
#    :!tag_Application_rsyslog:!tag_Application_pipeline:!tag_Layer_ecs:!platform_windows

- hosts:
    tag_tower_unixub
    :!platform_windows
#    tag_Environment_Prod
#    :tag_Environment_MGMT
#    :!tag_ServiceGroup_docker
#    :!tag_Application_rsyslog
#    :!tag_Application_pipeline
#    :!tag_Application_netherland
#    :!tag_Layer_ecs

  any_errors_fatal: true
  strategy: free
#  tags: dev
  roles:
    - role: reporting


- hosts: localhost
  connection: local
  tasks:
  - name: making one summary file
    delegate_to: localhost
    shell: echo $(head -n1 $(ls -1rt tmp/report-*.csv | head -n1)) > tmp/summary.csv && for f in tmp/report-*.csv; do tail -n1 "$f" >> tmp/summary.csv; done
  tags: always


# TODO:
# !us-east-1:
# !tag_Application_pipeline
# !tag_tower_unixub
# !tag_Layer_ecs
# !platform_windows
