---
- hosts: localhost
  tasks:
    - name: Prevent run without tags
      fail: msg="You must run this playbook with tags!"

- hosts: tag_Application_wordpress:&tag_Environment_Dev:&10.5.227.226
  tags: dev
  vars:
    management_user: www-mgmt
    sitename: dev.annalect.com
    post_upgrade_hardening_script_name: post_upgrade_harden.sh
    #### without trailing / ###################
    wordpress_path: /var/www/wordpress
    #########################################
  tasks:
    - debug: msg="Remember to deal with DEV2"

    - include_role:
        name: wordpress_update

- hosts: tag_Application_wordpress:&tag_Environment_Prod
  tags: prod
  vars:
    management_user: www-mgmt
    post_upgrade_hardening_script_name: post_upgrade_harden.sh
  tasks:
     - include_role:
         name: wordpress_update
       vars:
         sitename: "{{ item.sitename }}"
         wordpress_path: "{{ item.wordpress_path }}"
       with_items:
        - {sitename: "www.annalect.com", wordpress_path: "/var/www/wordpress"}

- hosts: tag_Application_wordpress:&tag_Environment_Dev
  tags: deveu
  vars:
    management_user: www-mgmt
    post_upgrade_hardening_script_name: post_upgrade_harden.sh
  tasks:
#    - debug: msg="{{ item.uno }} - {{ item.dos }}"
#      with_items:
#        - {uno: "uno", dos: "dos"}
#        - {uno: "tres", dos: "cuatro"}

     - include_role:
         name: wordpress_update
       vars:
         sitename: "{{ item.sitename }}"
         wordpress_path: "{{ item.wordpress_path }}"
       with_items:
        - {sitename: "dev.annalect.dk", wordpress_path: "/var/www/annalectdk"}
        - {sitename: "dev.annalect.de", wordpress_path: "/var/www/annalectde"}
        - {sitename: "dev.annalect.fi", wordpress_path: "/var/www/annalectfi"}
        - {sitename: "dev.annalect.nl", wordpress_path: "/var/www/annalectnl"}
        - {sitename: "dev.annalect.no", wordpress_path: "/var/www/annalectno"}
        - {sitename: "dev.annalect.se", wordpress_path: "/var/www/annalectse"}
        - {sitename: "dev.annalect.uk", wordpress_path: "/var/www/annalectuk"}

- hosts: tag_Application_wordpress:&tag_Environment_Prod
  tags: prodeu
  vars:
    management_user: www-mgmt
    post_upgrade_hardening_script_name: post_upgrade_harden.sh
  tasks:
     - include_role:
         name: wordpress_update
       vars:
         sitename: "{{ item.sitename }}"
         wordpress_path: "{{ item.wordpress_path }}"
       with_items:
        - {sitename: "www.annalect.dk", wordpress_path: "/var/www/annalectdk"}
        - {sitename: "www.annalect.fi", wordpress_path: "/var/www/annalectfi"}
        - {sitename: "www.annalect.no", wordpress_path: "/var/www/annalectno"}








