#!/bin/bash
REGION=`curl -s http://169.254.169.254/latest/dynamic/instance-identity/document|grep region|awk -F\" '{print $4}'`
echo "$0: Got AWS Region:$REGION"
case $REGION in
        eu-west-1)
	#Update timezone to GMT (London)
	echo "removing the existing timezone set"
	rm -rf /etc/localtime
	echo "Set the timezone to Europe/London time"
	echo "Europe/London" > /etc/timezone
	cp /usr/share/zoneinfo/Europe/London /etc/localtime
                ;;
        us-east-1)
	#Update timezone to EST
	echo "removing the existing timezone set"
	rm -rf /etc/localtime
	echo "Set the timezone to America/New_York time"
	echo "America/New_York" > /etc/timezone
	cp /usr/share/zoneinfo/America/New_York /etc/localtime
                ;;
        *)      PREFIX="NONE"
                ;;
        esac

#Get the set timezone
TZONE=`date | cut -d " " -f5`
echo "Timezone is set to $TZONE"
