#!/bin/bash
#Restrict access from AD domain user
project=$1
env=$2
if [ $# -ne 2 ]; then
        echo "Usage: $0 <project_name> <dev|qa|prod|mgmt>"
        echo "Example:./DomainUserRestriction cybage qa"
        exit 1
fi
if [ "$env" = "dev" ] || [ "$env" = "qa" ] || [ "$env" = "prod" ] || [ "$env" = "mgmt" ] ; then 

SUDOFILE="/etc/sudoers"
sudossh="%ANNALECTWW\\\linux_"$project"_"$env"_sudo"
echo -n "Restricting these AD Groups to SSH on this system: "
echo "ANNALECTWW\\annalect^infra" "annalectww\\linux_"$project"_"$env"_ssh" "annalectww\\linux_"$project"_"$env"_sudo"
echo "Following groups will be added to $SUDOFILE"
echo "$sudossh\n"

echo "#Domain Group Access" > /tmp/s.txt
case $env in
dev)
sudo /opt/pbis/bin/config RequireMembershipOf "ANNALECTWW\\annalect^infra" "annalectww\\linux_"$project"_"$env"_ssh" "annalectww\\linux_"$project"_"$env"_sudo"
cp -p $SUDOFILE /tmp/sudoers
echo "$sudossh DEV=(ALL) ALL" >> /tmp/s.txt
cat /tmp/s.txt >> /tmp/sudoers
sudo awk '!x[$0]++' /tmp/sudoers > /tmp/sudoers.1 && sudo cp /tmp/sudoers.1 $SUDOFILE && chmod 440 $SUDOFILE
;;
qa)
sudo /opt/pbis/bin/config RequireMembershipOf "ANNALECTWW\\annalect^infra" "annalectww\\linux_"$project"_"$env"_ssh" "annalectww\\linux_"$project"_"$env"_sudo"
cp -p $SUDOFILE /tmp/sudoers
echo "$sudossh QA=(ALL) ALL" >> /tmp/s.txt
cat /tmp/s.txt >> /tmp/sudoers
sudo awk '!x[$0]++' /tmp/sudoers > /tmp/sudoers.1 && sudo cp /tmp/sudoers.1 $SUDOFILE && chmod 440 $SUDOFILE
;;
prod)
sudo /opt/pbis/bin/config RequireMembershipOf "ANNALECTWW\\annalect^infra" "annalectww\\linux_"$project"_"$env"_ssh" "annalectww\\linux_"$project"_"$env"_sudo"
cp -p $SUDOFILE /tmp/sudoers
echo "$sudossh PROD=(ALL) ALL" >> /tmp/s.txt
cat /tmp/s.txt >> /tmp/sudoers
sudo awk '!x[$0]++' /tmp/sudoers > /tmp/sudoers.1 && sudo cp /tmp/sudoers.1 $SUDOFILE && chmod 440 $SUDOFILE
;;
mgmt)
sudo /opt/pbis/bin/config RequireMembershipOf "ANNALECTWW\\annalect^infra"
;;
*)
;;
esac
else 
echo "Invalid Environment" 
echo "Usage: $0 <project_name> <dev|qa|prod|mgmt>"
exit 1
fi
