#!/bin/bash
# This script is called to ensure that new hardened instance joins the AD
# and DNS successfully after comes up online.
# This script is common across Ubuntu, RHEL & Centos
# This script has to be executed manually by the default user on Ubuntu,CentOS
# & RHEL
# Using user with administrative rights on AD to join the instanc with the password set
# If there is any change in user or password, please update the script before
# execution

##Pre-installed PBIS pkg in hardened image.
#sudo wget https://github.com/BeyondTrust/pbis-open/releases/download/8.6.0/pbis-open-8.6.0.427.linux.x86_64.deb.sh
#sudo chmod +x pbis-open-8.6.0.427.linux.x86_64.deb.sh
#sudo ./pbis-open-8.6.0.427.linux.x86_64.deb.sh

#Join to Domain
echo "Make sure that hostname is set before joining machine to domain"
echo -n "Type the user name having adminstrative rights to run the command and press [ENTER]: "
read username
sudo /opt/pbis/bin/domainjoin-cli join annalectww.com $username
sudo /opt/pbis/bin/update-dns
sudo /opt/pbis/bin/config LoginShellTemplate /bin/bash
sudo /opt/pbis/bin/config HomeDirTemplate %H/%D/%U
sudo /opt/pbis/bin/ad-cache --delete-all
#Apply fix: Edit /etc/pam.d/common-session and change "session sufficient" line to session [success=ok default=ignore] pam_lsass.so

sudo domainjoin-cli query
if [ $? -eq 0 ]; then
echo "..."
echo "Host `hostname` joined the domain successfully"
fi

