---
- name: fail if mongodb backup not done
  fail: msg="Please run the playbook with extra-variable `mongodb_backup_done=True` to be sure you have taken a backup"
  when: mongodb_backup_done is not defined or not mongodb_backup_done

- name: including role `distupgrade`
  include_role:
    name: distupgrade
  # unhold_packages: False
  become: yes
  when:
    - ((ec2_tag_ServiceGroup is undefined) or (ec2_tag_ServiceGroup in ["general", "apache", "dsdk", "mesos-master", "mesos-slave", "analysis", "wellsfargo", "utility", "mongodb", "bamboo", "samba", "openvpn", "openswan"]))

#- fail: msg="fail"

- name: including role `apache`
  include_role:
    name: apache
  become: yes
  when: ec2_tag_ServiceGroup in ["apache"]

- name: including role `mesos_slave`
  include_role:
    name: mesos_slave
  # unhold_mesos_slave: False
  become: yes
  when: ec2_tag_ServiceGroup in ["mesos-slave"]

- name: including role `mesos_master`
  include_role:
    name: mesos_master
  become: yes
  when: ec2_tag_ServiceGroup in ["mesos-master"]
  tags: mesos_master

- name: including role `analysis`
  include_role:
    name: analysis
  become: yes
  when: ec2_tag_ServiceGroup in ["analysis"]

- name: including role `dsdk`
  include_role:
    name: dsdk
  become: yes
  when: ec2_tag_ServiceGroup in ["dsdk"]

- name: including role `wellsfargo`
  include_role:
    name: wellsfargo
  become: yes
  when: ec2_tag_ServiceGroup in ["wellsfargo"]

- name: including role `utility`
  include_role:
    name: utility
  become: yes
  when: ec2_tag_ServiceGroup in ["utility"]

- name: including role `mongodb`
  include_role:
    name: mongodb
  become: yes
  when: ec2_tag_ServiceGroup in ["mongodb"]

- name: including role `bamboo`
  include_role:
    name: bamboo
  become: yes
  when: ec2_tag_ServiceGroup in ["bamboo"]

- name: including role `samba`
  include_role:
    name: samba
  become: yes
  when: ec2_tag_ServiceGroup in ["samba"]

- name: including role `openvpn`
  include_role:
    name: openvpn
  become: yes
  when: ec2_tag_ServiceGroup in ["openvpn"]

- name: including role `openswan`
  include_role:
    name: openswan
  become: yes
  when: ec2_tag_ServiceGroup in ["openswan"]
