---
- hosts: tag_Environment_Prod:tag_Environment_QA:&tag_Application_ade:&tag_Layer_ingest
  tasks:
    - name: download sources
      shell: wget http://download.microsoft.com/download/B/C/D/BCDD264C-7517-4B7D-8159-C99FC5535680/RedHat6/msodbcsql-11.0.2270.0.tar.gz
      args:
        chdir: /opt
      become: yes

    - name: uncompress file
      shell: tar -zxvf msodbcsql-11.0.2270.0.tar.gz
      args:
        chdir: /opt
      become: yes

    - name: execute install
      shell: bash /opt/msodbcsql-11.0.2270.0/install.sh install --accept-license --force
      args:
        chdir: /opt/msodbcsql-11.0.2270.0/
      ignore_errors: yes
      become: yes

    - name: create symbolic links 1
      file:
        src: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
        dest: /usr/lib/x86_64-linux-gnu/libcrypto.so.10
        state: link
      become: yes

    - name: create symbolic links 2
      file:
        src: /lib/x86_64-linux-gnu/libssl.so.1.0.0
        dest: /usr/lib/x86_64-linux-gnu/libssl.so.10
        state: link
      become: yes

    - name: verify installation
      shell: odbcinst -q -d -n "ODBC Driver 11 for SQL Server"
      args:
        chdir: /opt/msodbcsql-11.0.2270.0/
      become: yes

    - name: configuration file
      copy:
        content: |
                  [ODBC Driver 17 for SQL Server]
                  Description=Microsoft ODBC Driver 17 for SQL Server
                  Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.1.so.0.1
                  UsageCount=1

                  [ODBC Driver 13 for SQL Server]
                  Description=Microsoft ODBC Driver 13 for SQL Server
                  Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.2
                  UsageCount=1

                  [ODBC Driver 11 for SQL Server]
                  Description=Microsoft ODBC Driver 11 for SQL Server
                  Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-11.0.so.2270.0
                  Threading=1
                  UsageCount=1

                  [FreeTDS]
                  Description        = FreeTDS unixODBC Driver
                  Driver        = /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so
                  Setup        = /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so
        dest: /etc/odbcinst.ini
        force: yes
        backup: yes
      become: yes

    - name: installing unixodbc-dev and odbcinst and tdsodbc
      shell: apt-get install unixodbc-dev odbcinst tdsodbc -y
      become: yes

    - name: installing pyodbc
      shell: pip install pyodbc
      become: yes

    - name: generating test file
      copy:
        content: |
                  import pyodbc
                  db = pyodbc.connect('DRIVER=FreeTDS;SERVER=10.32.6.45,1433;UID=AnnalectService;PWD=san3-calm;DATABASE=MPSC_Metadata;TDS_Version=8.0;',unicode_results=True)
                  cur = db.cursor()
                  cur.execute('SELECT TOP 1 * FROM MPSC_Datamart.dbo.v_Prisma_Annalect_PG_US')
                  for row in cur:
                   print row
        dest: /opt/test-odbc.py
      become: yes

    - name: test odbc
      shell: python test-odbc.py
      args:
        chdir: /opt
      become: yes
