#!/bin/bash
### Check arguments
if [ $# -ne 3 ]; then echo "USAGE: mongo_restore remote_db_name_to_restore Local_db_Dump_Path remote_mongo_server"
                      echo "Example: mongo_restore qa assembly /backup/mongodbbackup/qa/2014-06-01"; exit; fi
#DEV_NODE="mon1-db-z1a-de
#QA_NODE="mongo-n1-db-z1a-qa"
#PROD_NODE="mongo-n1-db-z1a-pr"
ENV=$1
dbName=$2
DumpPath=$3
USER=root
PASS=5wabh1mAn
if [ $ENV=qa ]; then NODE="mongo-n1-db-z1a-qa"; fi
if [ $ENV=prod ]; then NODE="mongo-n1-db-z1a-pr"; fi
#mongodump --host $NODE --port 27017 --db $dbName --out $RestorePath/
mongorestore --host $NODE --port 27017 --db $dbName --username $USER --password $PASS --drop $DumpPath/$dbName
