---
- name: check java running
  include_role:
    name: java

- name: check if bamboo process is running
  shell: ps -ef | if grep -q "[b]amboo"; then echo yes; else echo no; fi
  register: bamboo_running

- name: start first utility process if not running
  shell: nohup /bamboo/atlassian-bamboo-5.14.5/bin/start-bamboo.sh &
  when: bamboo_running.stdout == "no"

- name: check if bamboo process is running 2nd
  shell: ps -ef | if grep -q "[b]amboo"; then echo yes; else echo no; fi
  register: bamboo_running_2nd_check

- fail: msg="bamboo process not running"
  when: bamboo_running_2nd_check.stdout == "no"
