---
- name: stop mesos-master
  service:
    name: mesos-master
    state: stopped
  ignore_errors: yes
  tags: always

- name: stop marathon
  service:
    name: marathon
    state: stopped
  tags: always

- name: zookeeper service restart
  service:
    name: zookeeper
    state: restarted
  tags: always

- name: start mesos-master
  service:
    name: mesos-master
    state: started
  ignore_errors: yes
  tags: always

- name: check if mesos-master process is running
  shell: ps -ef | if grep -q "[m]esos-master"; then echo yes; else echo no; fi
  register: mesos_master_running
  tags: always

- fail: msg="mesos-master process not running"
  when: mesos_master_running.stdout == "no"
  tags: always

- name: marathon service running
  service:
    name: marathon
    state: started
  tags: always
